/**
 * Employees API
 * API specification for employees.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeRequest { 
    /**
     * Unique id for employee
     */
    id: number;
    /**
     * First name of employee
     */
    firstName: string;
    /**
     * Last name of employee
     */
    lastName: string;
    /**
     * Salary of employee
     */
    salary: number | null;
}

