/**
 * Employees API
 * API specification for employees.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvalidResponse { 
    /**
     * The response code. Will always have 400 as a value indicating technical field validation error.
     */
    responseCode: number;
    /**
     * Will always have *Invalid* as a value indicating that technical fields validations against the schema have failed. For example, if the request fields do not match the specified pattern.
     */
    status: string;
    /**
     * This field will indicate the failure reason.
     */
    reason: string;
}

