/**
 * Employees API
 * API specification for employees.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotFoundResponse { 
    /**
     * The response code. Will always have 404 as a value indicating that the requested resource was not found.
     */
    responseCode: number;
    /**
     * Will always have *NotFound* as a value indicating that the requested resource was not found.
     */
    status: string;
    /**
     * This field will indicate the reason why the resource was not found.
     */
    reason: string;
}

