apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-pv
spec:
  capacity:
    storage: {{ .Values.postgresqlVolume.persistentVolume.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgresqlVolume.persistentVolume.pathOnHost }}