apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: {{ .Release.Name }}-postgres-container
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.databaseName }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-username
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-password
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: {{ .Release.Name }}-postgres-persistent-storage
              mountPath: {{ .Values.postgresqlVolume.mountPath }}
      volumes:
        - name: {{ .Release.Name }}-postgres-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc
