/**
 * Employees API
 * API specification for employees.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EmployeeRequest } from '../model/models';
import { EmployeeResponse } from '../model/models';
import { ErrorResponse } from '../model/models';
import { InvalidResponse } from '../model/models';
import { NotFoundResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EmployeesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Find All Employees
     * Returns All the employees
     */
    allEmployees(extraHttpRequestParams?: any): Observable<Array<EmployeeResponse>>;

    /**
     * Create Employee
     * Add One Employee To The Company
     * @param employeeRequest 
     */
    createEmployee(employeeRequest: EmployeeRequest, extraHttpRequestParams?: any): Observable<EmployeeResponse>;

    /**
     * Delete Employee
     * Delete an existing employee
     * @param id The ID of the employee to delete
     */
    deleteEmployee(id: number, extraHttpRequestParams?: any): Observable<EmployeeResponse>;

}
